name: gtm_ios
description: Flutter gtm plugin ios
repository: https://github.com/Heewookji/gtm
issue_tracker: https://github.com/Heewookji/gtm/issues
version: 0.0.2

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: gtm
    platforms:
      ios:
        dartPluginClass: GtmIOS
        pluginClass: GtmIosPlugin

dependencies:
  flutter:
    sdk: flutter
  gtm_platform_interface:
    path: ../gtm_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
